export MasterPage from './MasterPage'
export IndexPage from './IndexPage'
export RegisterModal from './RegisterModal'
export LoginModal from './LoginModal'
export ResetPasswordPage from './ResetPasswordPage'
export VerifyEmailPage from './VerifyEmailPage'
export ProfilePage from './ProfilePage'
export ChangePasswordPage from './ChangePasswordPage'