export AdminLoginModal from './admin/AdminLoginModal'
export AdminRegisterModal from './admin/AdminRegisterModal'
export AdminPanel from './admin/AdminPanel'
export MasterPage from './MasterPage'
export IndexPage from './Home/IndexPage'
export UserRegisterModal from './Authenticate/UserRegisterModal'
export LoginModal from './Authenticate/LoginModal'
export ForgotPasswordModal from './Authenticate/ForgotPasswordModal'
export ResetPasswordPage from './Authenticate/ResetPasswordPage'
export VerifyEmailPage from './Authenticate/VerifyEmailPage'
export ChangePasswordPage from './Authenticate/ChangePasswordPage'
export UserProfilePage from './Profile/UserProfilePage'
export ProducerProfilePage from './Profile/ProducerProfilePage'
export ProfileContainer from './Profile/ProfileContainer'
export AddProduct from './Product/AddProduct'
export UserSettingPage from './UserSetting/UserSettingPage';
export Ingredients from './Product/Ingredients'
export DeliveryMethods from './Product/DeliveryMethods'
export ReactSlider from './Product/ReactSlider'
export UserHomePage from './AddProduct/UserHomePage'
export HelpPage from './SiteStaticPages/HelpPage';
export AboutPage from './SiteStaticPages/AboutPage';
export TermsPage from './SiteStaticPages/TermsPage';
export PrivacyPage from './SiteStaticPages/PrivacyPage';
export FaqPage from './SiteStaticPages/FaqPage';
export MapViewContainer from './Searching/MapViewContainer';
export DisplaySearch from './Searching/DisplaySearch';

